//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesiBireysel1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphane1Entities : DbContext
    {
        public kutuphane1Entities()
            : base("name=kutuphane1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YeniHbrHaberler> YeniHbrHaberler { get; set; }
        public virtual DbSet<YeniHbrKategoriler> YeniHbrKategoriler { get; set; }
        public virtual DbSet<YeniHbrYonetim> YeniHbrYonetim { get; set; }
        public virtual DbSet<YeniHbrYorumlar> YeniHbrYorumlar { get; set; }
        public virtual DbSet<YeniHbrUyeler> YeniHbrUyeler { get; set; }
    }
}
