//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesiBireysel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeniHbrHaberler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YeniHbrHaberler()
        {
            this.YeniHbrYorumlar = new HashSet<YeniHbrYorumlar>();
        }
    
        public int HaberID { get; set; }
        public string Baslik { get; set; }
        public string Ozet { get; set; }
        public string Icerik { get; set; }
        public string ResimYolu { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> OkunmaSayisi { get; set; }
        public Nullable<int> KategoriID { get; set; }
    
        public virtual YeniHbrKategoriler YeniHbrKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeniHbrYorumlar> YeniHbrYorumlar { get; set; }
    }
}
