//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesiBireysel1
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeniHbrYorumlar
    {
        public int YorumID { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string YorumMetni { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> OnayliMi { get; set; }
        public Nullable<int> HaberID { get; set; }
    
        public virtual YeniHbrHaberler YeniHbrHaberler { get; set; }
    }
}
